### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by amilasilva92** [Eniac-Xie/TEAM#2]
Great work! May I know when you are going to release the code?
Thanks.

**Comment by Eniac-Xie** [comment]
Hi, a new homepage of TEAM model (including our largest pre-trained model and code) can be found [here](https://modelscope.cn/models/damo/multi-modal_team-vit-large-patch14_multi-modal-similarity/summary).

Our code has been merged into [modelscope](https://github.com/modelscope/modelscope), code of TEAM model can be found [here](https://github.com/modelscope/modelscope/tree/master/modelscope/models/multi_modal/team), demo code can be found [here](https://github.com/modelscope/modelscope/blob/master/tests/pipelines/test_multi_modal_similarity.py).
