### ISSUE TITLE
How to find the code related to this project

### ISSUE THREAD

**Issue by skyABB** [Eniac-Xie/TEAM#3]
This work is great, I tried to look for this code from the integration library, but there are too many and did not find anything related to this project, I want to know the code related to the 

> **Token Embeddings Alignment** 

Module, I don't know if it is convenient to specify

**Comment by Eniac-Xie** [comment]
Hi @skyABB, sorry for the inconvenience!

**Comment by Eniac-Xie** [comment]
Hi @skyABB, sorry for the inconvenience!
The code related to the Token Embeddings Alignment module can be found here:
https://github.com/modelscope/modelscope/blob/master/modelscope/models/multi_modal/team/utils.py#L279

The 'get_cross_score' function takes text embeddings and image embeddings as input, align them by multi-head attention, then compute the similiary score. Figure 3 in our paper illustrate the process of the 'get_cross_score' function.

**Comment by Eniac-Xie** [comment]
Besides that, the core implementation of TEAM module is under this directory:
https://github.com/modelscope/modelscope/tree/master/modelscope/models/multi_modal/team
